use super::github_release::{
    ArchiveFormat, GithubReleaseSpec, ReleaseAssetSpec, ReleaseSelector, ReleaseTarget,
};
use super::github_specs::*;
use crate::language::LanguageKind;
use serde::Serialize;
use std::sync::LazyLock;

pub static REGISTRY: LazyLock<Registry> = LazyLock::new(Registry::default_registry);

const ALS_VERSION: &str = "2026.2.202604091";
const ALS_RELEASE_ASSETS: &[ReleaseAssetSpec] = &[
    ReleaseAssetSpec {
        target: ReleaseTarget::MacosX64,
        asset_name: "als-2026.2.202604091-darwin-x64.tar.gz",
        archive_format: ArchiveFormat::TarGz,
        binary_path: "integration/vscode/ada/x64/darwin/ada_language_server",
        sha256: None,
    },
    ReleaseAssetSpec {
        target: ReleaseTarget::MacosArm64,
        asset_name: "als-2026.2.202604091-darwin-arm64.tar.gz",
        archive_format: ArchiveFormat::TarGz,
        binary_path: "integration/vscode/ada/arm64/darwin/ada_language_server",
        sha256: None,
    },
    ReleaseAssetSpec {
        target: ReleaseTarget::LinuxX64Gnu,
        asset_name: "als-2026.2.202604091-linux-x64.tar.gz",
        archive_format: ArchiveFormat::TarGz,
        binary_path: "integration/vscode/ada/x64/linux/ada_language_server",
        sha256: None,
    },
    ReleaseAssetSpec {
        target: ReleaseTarget::LinuxArm64Gnu,
        asset_name: "als-2026.2.202604091-linux-arm64.tar.gz",
        archive_format: ArchiveFormat::TarGz,
        binary_path: "integration/vscode/ada/arm64/linux/ada_language_server",
        sha256: None,
    },
    ReleaseAssetSpec {
        target: ReleaseTarget::WindowsX64,
        asset_name: "als-2026.2.202604091-win32-x64.tar.gz",
        archive_format: ArchiveFormat::TarGz,
        binary_path: "integration/vscode/ada/x64/win32/ada_language_server.exe",
        sha256: None,
    },
];
const ALS_RELEASE_SPEC: GithubReleaseSpec = GithubReleaseSpec {
    owner: "AdaCore",
    repo: "ada_language_server",
    selector: ReleaseSelector::Tag(ALS_VERSION),
    max_size_bytes: 256 * 1024 * 1024,
    max_extract_size_bytes: 512 * 1024 * 1024,
    install_warning: None,
    assets: ALS_RELEASE_ASSETS,
};

#[derive(Debug)]
pub struct Registry {
    entries: Vec<ServerEntry>,
}

impl Registry {
    fn default_registry() -> Self {
        Self {
            entries: vec![
                npm_entry(
                    "typescript-language-server",
                    "typescript-language-server",
                    LanguageKind::TypeScript,
                    "typescript-language-server",
                    &["typescript-language-server"],
                    "latest",
                    &["typescript-language-server", "typescript"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/typescript-language-server/typescript-language-server",
                    "Thin standard-LSP wrapper over TypeScript tsserver, giving strong JS/TS semantics with an npm-sized footprint.",
                ),
                npm_entry(
                    "javascript-language-server",
                    "typescript-language-server",
                    LanguageKind::JavaScript,
                    "typescript-language-server",
                    &["typescript-language-server"],
                    "latest",
                    &["typescript-language-server", "typescript"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/typescript-language-server/typescript-language-server",
                    "The same tsserver-backed LSP is the strongest compact choice for JavaScript projects.",
                ),
                npm_entry(
                    "pyright",
                    "pyright-langserver",
                    LanguageKind::Python,
                    "pyright-langserver",
                    &["pyright-langserver"],
                    "latest",
                    &["pyright"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/microsoft/pyright",
                    "Full-featured, standards-based Python type intelligence; Ruff is lighter but not a semantic replacement.",
                ),
                github_release_entry(
                    "rust-analyzer",
                    "rust-analyzer",
                    LanguageKind::Rust,
                    "rust-analyzer",
                    &["rust-analyzer"],
                    RUST_ANALYZER_VERSION,
                    &RUST_ANALYZER_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://rust-analyzer.github.io/",
                    "Compiler-adjacent Rust LSP with broad editor support.",
                ),
                go_entry(
                    "gopls",
                    "gopls",
                    LanguageKind::Go,
                    "gopls",
                    &["gopls"],
                    "latest",
                    "golang.org/x/tools/gopls",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://pkg.go.dev/golang.org/x/tools/gopls",
                    "Official Go Team language server; installs as one binary when the Go toolchain is already present.",
                ),
                manual_entry(
                    "jdtls",
                    "Eclipse JDT LS",
                    LanguageKind::Java,
                    "jdtls",
                    &["jdtls"],
                    "system",
                    Footprint::High,
                    Maturity::Stable,
                    "https://github.com/eclipse-jdtls/eclipse.jdt.ls",
                    "Most complete Java LSP, including Maven and Gradle support.",
                    "Install Eclipse JDT LS or a distribution package that provides `jdtls` on PATH.",
                ),
                dotnet_entry(
                    "csharp-ls",
                    "csharp-ls",
                    LanguageKind::CSharp,
                    "csharp-ls",
                    &["csharp-ls"],
                    "latest",
                    "csharp-ls",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/razzmatazz/csharp-language-server",
                    "Roslyn-based standard LSP with a smaller footprint than OmniSharp or C# Dev Kit.",
                ),
                gem_entry(
                    "ruby-lsp",
                    "ruby-lsp",
                    LanguageKind::Ruby,
                    "ruby-lsp",
                    &["ruby-lsp"],
                    "latest",
                    "ruby-lsp",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://shopify.github.io/ruby-lsp/",
                    "Modern Ruby LSP with broad navigation, diagnostics, formatting, and add-on support.",
                ),
                manual_entry(
                    "kotlin-lsp",
                    "kotlin-lsp",
                    LanguageKind::Kotlin,
                    "kotlin-lsp",
                    &["kotlin-lsp", "kotlin-language-server"],
                    "system",
                    Footprint::High,
                    Maturity::Preview,
                    "https://github.com/Kotlin/kotlin-lsp",
                    "Official JetBrains LSP is the right long-term candidate, but its archive layout is not yet a low-risk managed install.",
                    "Install JetBrains Kotlin LSP standalone archive or put a compatible Kotlin language server on PATH.",
                ),
                github_release_entry(
                    "clangd",
                    "clangd",
                    LanguageKind::Cpp,
                    "clangd",
                    &["clangd"],
                    LLVM_CLANGD_VERSION,
                    &LLVM_CLANGD_RELEASE_SPEC,
                    Footprint::High,
                    Maturity::Stable,
                    "https://clangd.llvm.org/",
                    "LLVM-backed C/C++ language server with the strongest semantic model.",
                ),
                manual_entry(
                    "metals",
                    "Metals",
                    LanguageKind::Scala,
                    "metals",
                    &["metals"],
                    "system",
                    Footprint::High,
                    Maturity::Stable,
                    "https://scalameta.org/metals/",
                    "Scala Center/Scalameta language server with rich build-tool integration.",
                    "Install Metals through Coursier or your editor tooling, then ensure `metals` is on PATH.",
                ),
                github_release_entry(
                    "lua-language-server",
                    "lua-language-server",
                    LanguageKind::Lua,
                    "lua-language-server",
                    &["lua-language-server"],
                    LUA_LS_VERSION,
                    &LUA_LS_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://luals.github.io/",
                    "LuaLS provides annotations, type-aware diagnostics, completion, hover, and formatting with a compact native runtime.",
                ),
                manual_entry(
                    "sourcekit-lsp",
                    "sourcekit-lsp",
                    LanguageKind::Swift,
                    "sourcekit-lsp",
                    &["sourcekit-lsp"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/swiftlang/sourcekit-lsp",
                    "Official Swift LSP with high-fidelity support; duplicating the Swift toolchain would waste disk.",
                    "Install the Swift toolchain or Xcode; SourceKit-LSP is bundled there and should be on PATH.",
                ),
                manual_entry(
                    "phpactor",
                    "phpactor",
                    LanguageKind::Php,
                    "phpactor",
                    &["phpactor"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/phpactor/phpactor",
                    "Open-source PHP LSP with stronger IDE semantics than lint-only servers and less lock-in than proprietary alternatives.",
                    "Install phpactor through Composer or a PHAR release, then ensure `phpactor` is on PATH.",
                ),
                github_release_entry(
                    "ada-language-server",
                    "Ada Language Server",
                    LanguageKind::Ada,
                    "ada_language_server",
                    &["ada_language_server", "als"],
                    ALS_VERSION,
                    &ALS_RELEASE_SPEC,
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/AdaCore/ada_language_server",
                    "AdaCore-maintained Ada/SPARK language server and the strongest standards-aligned choice.",
                ),
                npm_entry(
                    "bash-language-server",
                    "bash-language-server",
                    LanguageKind::Bash,
                    "bash-language-server",
                    &["bash-language-server"],
                    "latest",
                    &["bash-language-server"],
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/bash-lsp/bash-language-server",
                    "Widely adopted shell LSP with a small npm footprint.",
                ),
                github_release_entry(
                    "clojure-lsp",
                    "clojure-lsp",
                    LanguageKind::Clojure,
                    "clojure-lsp",
                    &["clojure-lsp"],
                    CLOJURE_LSP_VERSION,
                    &CLOJURE_LSP_RELEASE_SPEC,
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/clojure-lsp/clojure-lsp",
                    "Clojure-focused LSP with broad editor support and project-aware analysis.",
                ),
                manual_entry(
                    "dart-sdk-lsp",
                    "Dart SDK language server",
                    LanguageKind::Dart,
                    "dart",
                    &["dart"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/dart-lang/sdk",
                    "Official Dart analysis server shipped with the Dart SDK.",
                    "Install the Dart SDK or Flutter SDK and ensure `dart` is on PATH.",
                ),
                github_release_entry(
                    "deno-lsp",
                    "deno lsp",
                    LanguageKind::Deno,
                    "deno",
                    &["deno"],
                    DENO_VERSION,
                    &DENO_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/denoland/deno",
                    "Official Deno language server built into the Deno runtime.",
                ),
                github_release_entry(
                    "expert",
                    "Expert",
                    LanguageKind::Elixir,
                    "expert",
                    &["expert", "elixir-ls"],
                    EXPERT_VERSION,
                    &EXPERT_RELEASE_SPEC,
                    Footprint::Medium,
                    Maturity::Preview,
                    "https://github.com/elixir-lang/expert",
                    "Elixir team language server is the best long-term candidate; ElixirLS remains the fallback where Expert is not ready.",
                ),
                manual_entry(
                    "elp",
                    "Erlang Language Platform",
                    LanguageKind::Erlang,
                    "elp",
                    &["elp", "erlang_ls"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/WhatsApp/erlang-language-platform",
                    "Modern Erlang language platform with stronger active maintenance than older Erlang LS choices.",
                    "Install ELP or erlang_ls with upstream release/package-manager instructions and ensure the binary is on PATH.",
                ),
                dotnet_entry(
                    "fsautocomplete",
                    "FsAutoComplete",
                    LanguageKind::FSharp,
                    "fsautocomplete",
                    &["fsautocomplete"],
                    "latest",
                    "fsautocomplete",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/ionide/FsAutoComplete",
                    "Established F# LSP used by Ionide, installable as a .NET tool.",
                ),
                pipx_entry(
                    "fortls",
                    "fortls",
                    LanguageKind::Fortran,
                    "fortls",
                    &["fortls"],
                    "latest",
                    "fortls",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/fortran-lang/fortls",
                    "Fortran-lang maintained LSP with a compact Python package footprint.",
                ),
                manual_entry(
                    "haskell-language-server",
                    "Haskell Language Server",
                    LanguageKind::Haskell,
                    "haskell-language-server-wrapper",
                    &["haskell-language-server-wrapper", "haskell-language-server"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/haskell/haskell-language-server",
                    "Canonical Haskell IDE engine with build-tool integration.",
                    "Install HLS through GHCup or your package manager, then ensure `haskell-language-server-wrapper` is on PATH.",
                ),
                manual_entry(
                    "julia-language-server",
                    "LanguageServer.jl",
                    LanguageKind::Julia,
                    "julia-language-server",
                    &["julia-language-server"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/julia-vscode/LanguageServer.jl",
                    "Julia's mature language server package runs through the Julia toolchain.",
                    "Install Julia and LanguageServer.jl using the upstream editor/tooling instructions.",
                ),
                github_release_entry(
                    "nimlangserver",
                    "nimlangserver",
                    LanguageKind::Nim,
                    "nimlangserver",
                    &["nimlangserver"],
                    NIMLANGSERVER_VERSION,
                    &NIMLANGSERVER_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/nim-lang/langserver",
                    "Nim language server maintained under the Nim organization.",
                ),
                manual_entry(
                    "ocamllsp",
                    "ocamllsp",
                    LanguageKind::Ocaml,
                    "ocamllsp",
                    &["ocamllsp"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/ocaml/ocaml-lsp",
                    "Official OCaml Platform language server for OCaml and Reason workflows.",
                    "Install ocaml-lsp-server through opam and ensure `ocamllsp` is on PATH.",
                ),
                github_release_entry(
                    "perl-navigator",
                    "Perl Navigator",
                    LanguageKind::Perl,
                    "perlnavigator",
                    &["perlnavigator"],
                    PERL_NAVIGATOR_VERSION,
                    &PERL_NAVIGATOR_RELEASE_SPEC,
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/bscan/PerlNavigator",
                    "Actively maintained Perl LSP with navigation and diagnostics.",
                ),
                manual_entry(
                    "powershell-editor-services",
                    "PowerShell Editor Services",
                    LanguageKind::PowerShell,
                    "PowerShellEditorServices",
                    &["PowerShellEditorServices", "Start-EditorServices.ps1"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/PowerShell/PowerShellEditorServices",
                    "Microsoft-maintained PowerShell language service delivered through the PowerShell toolchain.",
                    "Install PowerShell Editor Services through PowerShell tooling or your editor integration; `pwsh` should be on PATH.",
                ),
                manual_entry(
                    "r-languageserver",
                    "R languageserver",
                    LanguageKind::R,
                    "R-languageserver",
                    &["R-languageserver", "languageserver"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/REditorSupport/languageserver",
                    "Mature R LSP package with broad editor support.",
                    "Install R and run `install.packages(\"languageserver\")`, then ensure R is on PATH.",
                ),
                manual_entry(
                    "racket-langserver",
                    "racket-langserver",
                    LanguageKind::Racket,
                    "racket-langserver",
                    &["racket-langserver"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/jeapostrophe/racket-langserver",
                    "Dedicated Racket LSP with package-manager installation.",
                    "Install racket-langserver with Racket package tools and ensure `racket-langserver` is on PATH.",
                ),
                manual_entry(
                    "raku-navigator",
                    "Raku Navigator",
                    LanguageKind::Raku,
                    "raku-navigator",
                    &["raku-navigator"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/bscan/RakuNavigator",
                    "Raku-specific language server from the Perl Navigator maintainer.",
                    "Install Raku Navigator with upstream instructions and ensure `raku-navigator` is on PATH.",
                ),
                manual_entry(
                    "rescript-language-server",
                    "ReScript language server",
                    LanguageKind::ReScript,
                    "rescript-language-server",
                    &["rescript-language-server"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/rescript-lang/rescript-vscode",
                    "Official ReScript language tooling from the ReScript project.",
                    "Install ReScript editor tooling or language server and ensure `rescript-language-server` is on PATH.",
                ),
                github_release_entry(
                    "v-analyzer",
                    "v-analyzer",
                    LanguageKind::V,
                    "v-analyzer",
                    &["v-analyzer"],
                    V_ANALYZER_VERSION,
                    &V_ANALYZER_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/vlang/v-analyzer",
                    "Maintained V language server with better current support than the older vls.",
                ),
                manual_entry(
                    "vala-language-server",
                    "vala-language-server",
                    LanguageKind::Vala,
                    "vala-language-server",
                    &["vala-language-server"],
                    "system",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/vala-lang/vala-language-server",
                    "Vala project language server with code intelligence for Vala and Genie.",
                    "Install vala-language-server with your package manager or upstream release and ensure it is on PATH.",
                ),
                github_release_entry(
                    "zls",
                    "zls",
                    LanguageKind::Zig,
                    "zls",
                    &["zls"],
                    ZLS_VERSION,
                    &ZLS_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/zigtools/zls",
                    "Canonical Zig language server maintained by zigtools.",
                ),
                manual_entry(
                    "nil",
                    "nil",
                    LanguageKind::Nix,
                    "nil",
                    &["nil"],
                    "system",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/oxalica/nil",
                    "Rust-based Nix language server with a smaller footprint than nixd.",
                    "Install nil through Nix, Mason, or your package manager and ensure `nil` is on PATH.",
                ),
                manual_entry(
                    "ballerina-language-server",
                    "Ballerina Language Server",
                    LanguageKind::Ballerina,
                    "bal",
                    &["bal"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/ballerina-platform/ballerina-lang",
                    "Official Ballerina language server shipped with the Ballerina distribution.",
                    "Install Ballerina and ensure `bal` is on PATH.",
                ),
                manual_entry(
                    "chapel-language-server",
                    "Chapel Language Server",
                    LanguageKind::Chapel,
                    "chapel-language-server",
                    &["chapel-language-server"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/chapel-lang/chapel",
                    "Official Chapel language server in the Chapel ecosystem.",
                    "Install Chapel language tooling and ensure `chapel-language-server` is on PATH.",
                ),
                manual_entry(
                    "crystalline",
                    "Crystalline",
                    LanguageKind::Crystal,
                    "crystalline",
                    &["crystalline"],
                    "system",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/elbywan/crystalline",
                    "Most capable maintained Crystal LSP compared with older Scry installs.",
                    "Install Crystalline through shards, releases, or package manager and ensure `crystalline` is on PATH.",
                ),
                github_release_entry(
                    "serve-d",
                    "serve-d",
                    LanguageKind::Dlang,
                    "serve-d",
                    &["serve-d"],
                    SERVE_D_VERSION,
                    &SERVE_D_RELEASE_SPEC,
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/Pure-D/serve-d",
                    "Widely used D language server with DUB integration.",
                ),
                npm_entry(
                    "elm-language-server",
                    "elm-language-server",
                    LanguageKind::Elm,
                    "elm-language-server",
                    &["elm-language-server"],
                    "latest",
                    &["@elm-tooling/elm-language-server"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/elm-tooling/elm-language-server",
                    "Elm tooling language server with a clean npm package and predictable binary.",
                ),
                github_release_entry(
                    "gleam-lsp",
                    "Gleam language server",
                    LanguageKind::Gleam,
                    "gleam",
                    &["gleam"],
                    GLEAM_VERSION,
                    &GLEAM_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/gleam-lang/gleam",
                    "Official Gleam LSP is built into the Gleam compiler command.",
                ),
                manual_entry(
                    "groovy-language-server",
                    "Groovy Language Server",
                    LanguageKind::Groovy,
                    "groovy-language-server",
                    &["groovy-language-server"],
                    "system",
                    Footprint::High,
                    Maturity::Stable,
                    "https://github.com/GroovyLanguageServer/groovy-language-server",
                    "Community Groovy LSP with the broadest standalone editor support.",
                    "Install Groovy Language Server with upstream instructions and ensure the launch command is on PATH.",
                ),
                manual_entry(
                    "haxe-language-server",
                    "Haxe Language Server",
                    LanguageKind::Haxe,
                    "haxe-language-server",
                    &["haxe-language-server"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/vshaxe/haxe-language-server",
                    "Haxe Foundation language server used by vshaxe.",
                    "Install Haxe and haxe-language-server with haxelib/upstream instructions and ensure the binary is on PATH.",
                ),
                manual_entry(
                    "idris2-lsp",
                    "idris2-lsp",
                    LanguageKind::Idris2,
                    "idris2-lsp",
                    &["idris2-lsp"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/idris-community/idris2-lsp",
                    "Canonical Idris2 language server maintained by the Idris community.",
                    "Install idris2-lsp with Idris2 package tooling and ensure `idris2-lsp` is on PATH.",
                ),
                manual_entry(
                    "lean-language-server",
                    "Lean 4 language server",
                    LanguageKind::Lean4,
                    "lake",
                    &["lake", "lean"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/leanprover/lean4",
                    "Official Lean 4 server shipped with the Lean toolchain.",
                    "Install Lean 4 with elan and ensure `lake` or `lean` is on PATH.",
                ),
                manual_entry(
                    "coq-lsp",
                    "coq-lsp",
                    LanguageKind::Coq,
                    "coq-lsp",
                    &["coq-lsp"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/ejgallego/coq-lsp",
                    "Modern Coq LSP with active development.",
                    "Install coq-lsp through opam and ensure `coq-lsp` is on PATH.",
                ),
                manual_entry(
                    "cl-lsp",
                    "cl-lsp",
                    LanguageKind::CommonLisp,
                    "cl-lsp",
                    &["cl-lsp"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/cxxxr/cl-lsp",
                    "Common Lisp language server with standalone LSP support.",
                    "Install cl-lsp with upstream instructions and ensure `cl-lsp` is on PATH.",
                ),
                github_release_entry(
                    "millet",
                    "Millet",
                    LanguageKind::StandardMl,
                    "millet-ls",
                    &["millet-ls", "millet"],
                    MILLET_VERSION,
                    &MILLET_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/azdavis/millet",
                    "Actively maintained Standard ML language server.",
                ),
                npm_entry(
                    "html-language-server",
                    "vscode-html-language-server",
                    LanguageKind::Html,
                    "vscode-html-language-server",
                    &["vscode-html-language-server"],
                    "latest",
                    &["vscode-langservers-extracted"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/hrsh7th/vscode-langservers-extracted",
                    "Extracted Microsoft HTML language server with strong ecosystem compatibility.",
                ),
                npm_entry(
                    "css-language-server",
                    "vscode-css-language-server",
                    LanguageKind::Css,
                    "vscode-css-language-server",
                    &["vscode-css-language-server"],
                    "latest",
                    &["vscode-langservers-extracted"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/hrsh7th/vscode-langservers-extracted",
                    "Extracted Microsoft CSS/Less/Sass language server with one shared npm install.",
                ),
                npm_entry(
                    "json-language-server",
                    "vscode-json-language-server",
                    LanguageKind::Json,
                    "vscode-json-language-server",
                    &["vscode-json-language-server"],
                    "latest",
                    &["vscode-langservers-extracted"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/hrsh7th/vscode-langservers-extracted",
                    "Extracted Microsoft JSON language server with schema support.",
                ),
                npm_entry(
                    "angular-language-server",
                    "Angular Language Server",
                    LanguageKind::Angular,
                    "ngserver",
                    &["ngserver"],
                    "latest",
                    &["@angular/language-server"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://angular.dev/tools/language-service",
                    "Official Angular language service for templates and Angular projects.",
                ),
                npm_entry(
                    "astro-language-server",
                    "Astro Language Server",
                    LanguageKind::Astro,
                    "astro-ls",
                    &["astro-ls"],
                    "latest",
                    &["@astrojs/language-server"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/withastro/language-tools",
                    "Official Astro language tooling with a clean npm server package.",
                ),
                npm_entry(
                    "svelte-language-server",
                    "Svelte Language Server",
                    LanguageKind::Svelte,
                    "svelteserver",
                    &["svelteserver"],
                    "latest",
                    &["svelte-language-server"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/sveltejs/language-tools",
                    "Official Svelte language tools server.",
                ),
                npm_entry(
                    "vue-language-server",
                    "Vue Language Server",
                    LanguageKind::Vue,
                    "vue-language-server",
                    &["vue-language-server"],
                    "latest",
                    &["@vue/language-server"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/vuejs/language-tools",
                    "Official Vue language tools server and the successor to Vetur.",
                ),
                npm_entry(
                    "mdx-language-server",
                    "MDX Language Server",
                    LanguageKind::Mdx,
                    "mdx-language-server",
                    &["mdx-language-server"],
                    "latest",
                    &["@mdx-js/language-server"],
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/mdx-js/mdx-analyzer",
                    "MDX team language server for MDX content and JSX-in-Markdown workflows.",
                ),
                npm_entry(
                    "tailwindcss-language-server",
                    "Tailwind CSS Language Server",
                    LanguageKind::TailwindCss,
                    "tailwindcss-language-server",
                    &["tailwindcss-language-server"],
                    "latest",
                    &["@tailwindcss/language-server"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/tailwindlabs/tailwindcss-intellisense",
                    "Official Tailwind Labs language server for Tailwind-aware completions and diagnostics.",
                ),
                npm_entry(
                    "emmet-language-server",
                    "emmet-language-server",
                    LanguageKind::Emmet,
                    "emmet-language-server",
                    &["emmet-language-server"],
                    "latest",
                    &["@olrtg/emmet-language-server"],
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/olrtg/emmet-language-server",
                    "Small standalone Emmet LSP for HTML/CSS-style abbreviation expansion.",
                ),
                npm_entry(
                    "graphql-language-service-cli",
                    "GraphQL Language Service",
                    LanguageKind::GraphQl,
                    "graphql-lsp",
                    &["graphql-lsp"],
                    "latest",
                    &["graphql-language-service-cli"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/graphql/graphiql/tree/main/packages/graphql-language-service-cli",
                    "Official GraphQL Foundation language service CLI.",
                ),
                npm_entry(
                    "yaml-language-server",
                    "yaml-language-server",
                    LanguageKind::Yaml,
                    "yaml-language-server",
                    &["yaml-language-server"],
                    "latest",
                    &["yaml-language-server"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/redhat-developer/yaml-language-server",
                    "Red Hat YAML language server with JSON schema support.",
                ),
                manual_entry(
                    "lemminx",
                    "LemMinX XML Language Server",
                    LanguageKind::Xml,
                    "lemminx",
                    &["lemminx"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/eclipse-lemminx/lemminx",
                    "Most mature open XML language server.",
                    "Install LemMinX through your package manager, SDKMAN/Mason, or upstream release and ensure `lemminx` is on PATH.",
                ),
                github_release_entry(
                    "taplo",
                    "Taplo",
                    LanguageKind::Toml,
                    "taplo",
                    &["taplo"],
                    TAPLO_VERSION,
                    &TAPLO_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/tamasfe/taplo",
                    "Rust-based TOML language server with low footprint and formatting support.",
                ),
                github_release_entry(
                    "docker-language-server",
                    "Docker Language Server",
                    LanguageKind::Docker,
                    "docker-language-server",
                    &["docker-language-server"],
                    DOCKER_LS_VERSION,
                    &DOCKER_LS_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/docker/docker-language-server",
                    "Official Docker-maintained language server for Dockerfile, Compose, and Bake.",
                ),
                npm_entry(
                    "dockerfile-language-server",
                    "dockerfile-language-server",
                    LanguageKind::Docker,
                    "docker-langserver",
                    &["docker-langserver"],
                    "latest",
                    &["dockerfile-language-server-nodejs"],
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/rcjsuen/dockerfile-language-server-nodejs",
                    "Legacy Dockerfile-only npm server kept as a low-risk managed fallback.",
                ),
                manual_entry(
                    "terraform-ls",
                    "terraform-ls",
                    LanguageKind::Terraform,
                    "terraform-ls",
                    &["terraform-ls"],
                    "system",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/hashicorp/terraform-ls",
                    "HashiCorp-maintained Terraform language server.",
                    "Install terraform-ls through HashiCorp releases, Homebrew, Scoop, or your package manager and ensure it is on PATH.",
                ),
                github_release_entry(
                    "cue-lsp",
                    "CUE language server",
                    LanguageKind::Cue,
                    "cue",
                    &["cue"],
                    CUE_VERSION,
                    &CUE_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/cue-lang/cue",
                    "Official CUE tooling includes language-server support.",
                ),
                go_entry(
                    "jsonnet-language-server",
                    "jsonnet-language-server",
                    LanguageKind::Jsonnet,
                    "jsonnet-language-server",
                    &["jsonnet-language-server"],
                    "latest",
                    "github.com/grafana/jsonnet-language-server",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/grafana/jsonnet-language-server",
                    "Grafana-maintained Jsonnet LSP with a stable Go module install path.",
                ),
                github_release_entry(
                    "kcl-language-server",
                    "KCL Language Server",
                    LanguageKind::Kcl,
                    "kcl-language-server",
                    &["kcl-language-server"],
                    KCL_VERSION,
                    &KCL_RELEASE_SPEC,
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/kcl-lang/kcl",
                    "Official KCL language server for configuration-heavy projects.",
                ),
                manual_entry(
                    "bicep-language-server",
                    "Bicep Language Server",
                    LanguageKind::Bicep,
                    "bicep-langserver",
                    &["bicep-langserver", "bicep"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/Azure/bicep",
                    "Microsoft-maintained Bicep language server tied to the Bicep toolchain.",
                    "Install Bicep CLI/language server with Azure tooling or a package manager and ensure the launcher is on PATH.",
                ),
                manual_entry(
                    "ansible-language-server",
                    "ansible-language-server",
                    LanguageKind::Ansible,
                    "ansible-language-server",
                    &["ansible-language-server"],
                    "system",
                    Footprint::High,
                    Maturity::Stable,
                    "https://github.com/ansible/vscode-ansible",
                    "Ansible language server is useful but often depends on Python/Ansible project tooling, so LSP-IO only guides it for now.",
                    "Install ansible-language-server and its Ansible dependencies with upstream instructions, then ensure `ansible-language-server` is on PATH.",
                ),
                github_release_entry(
                    "helm-ls",
                    "helm-ls",
                    LanguageKind::Helm,
                    "helm_ls",
                    &["helm_ls", "helm-ls"],
                    HELM_LS_VERSION,
                    &HELM_LS_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/mrjosh/helm-ls",
                    "Go-based Helm language server for chart templates and values.",
                ),
                github_release_entry(
                    "neocmakelsp",
                    "neocmakelsp",
                    LanguageKind::CMake,
                    "neocmakelsp",
                    &["neocmakelsp"],
                    NEOCMAKELSP_VERSION,
                    &NEOCMAKELSP_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/Decodetalkers/neocmakelsp",
                    "Rust CMake server with a smaller footprint than older Python alternatives.",
                ),
                github_release_entry(
                    "mesonlsp",
                    "mesonlsp",
                    LanguageKind::Meson,
                    "mesonlsp",
                    &["mesonlsp"],
                    MESONLSP_VERSION,
                    &MESONLSP_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/JCWasmx86/mesonlsp",
                    "Dedicated Meson language server.",
                ),
                github_release_entry(
                    "just-lsp",
                    "just-lsp",
                    LanguageKind::Just,
                    "just-lsp",
                    &["just-lsp"],
                    JUST_LSP_VERSION,
                    &JUST_LSP_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/terror/just-lsp",
                    "Small Justfile language server.",
                ),
                manual_entry(
                    "make-lsp",
                    "make-lsp",
                    LanguageKind::Make,
                    "make-lsp",
                    &["make-lsp"],
                    "system",
                    Footprint::Low,
                    Maturity::Preview,
                    "https://github.com/alexclewontin/make-lsp-vscode",
                    "Only viable Makefile-specific LSP surfaced in public registries; keep manual due young package shape.",
                    "Install make-lsp with upstream instructions and ensure `make-lsp` is on PATH.",
                ),
                pipx_entry(
                    "nginx-language-server",
                    "nginx-language-server",
                    LanguageKind::Nginx,
                    "nginx-language-server",
                    &["nginx-language-server"],
                    "latest",
                    "nginx-language-server",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/pappasam/nginx-language-server",
                    "Compact Python LSP for nginx.conf with a stable package-manager path.",
                ),
                pipx_entry(
                    "systemd-language-server",
                    "systemd-language-server",
                    LanguageKind::Systemd,
                    "systemd-language-server",
                    &["systemd-language-server"],
                    "latest",
                    "systemd-language-server",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/psacawa/systemd-language-server",
                    "Small Python LSP for systemd unit files.",
                ),
                manual_entry(
                    "github-actions-language-server",
                    "GitHub Actions Language Server",
                    LanguageKind::GitHubActions,
                    "gh-actions-language-server",
                    &["gh-actions-language-server"],
                    "system",
                    Footprint::Low,
                    Maturity::Preview,
                    "https://github.com/actions/languageservices",
                    "GitHub's language service is official, but standalone executable packaging is still wrapper-based.",
                    "Install @actions/languageserver or a maintained wrapper and ensure the server command is on PATH.",
                ),
                manual_entry(
                    "gitlab-ci-ls",
                    "gitlab-ci-ls",
                    LanguageKind::GitLabCi,
                    "gitlab-ci-ls",
                    &["gitlab-ci-ls"],
                    "system",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/alesbrelih/gitlab-ci-ls",
                    "Dedicated GitLab CI language server with cross-platform package-manager availability.",
                    "Install gitlab-ci-ls through conda, Nix, or upstream instructions and ensure `gitlab-ci-ls` is on PATH.",
                ),
                github_release_entry(
                    "buf-language-server",
                    "Buf Language Server",
                    LanguageKind::Protobuf,
                    "buf",
                    &["buf"],
                    BUF_VERSION,
                    &BUF_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/bufbuild/buf",
                    "Buf-maintained language server is the strongest modern Protocol Buffers option.",
                ),
                go_entry(
                    "thrift-ls",
                    "thrift-ls",
                    LanguageKind::Thrift,
                    "thrift-ls",
                    &["thrift-ls"],
                    "latest",
                    "github.com/joyme123/thrift-ls",
                    Footprint::Low,
                    Maturity::Preview,
                    "https://github.com/joyme123/thrift-ls",
                    "Go Thrift language server with straightforward module install; marked preview due smaller ecosystem.",
                ),
                go_entry(
                    "sqls",
                    "sqls",
                    LanguageKind::Sql,
                    "sqls",
                    &["sqls"],
                    "latest",
                    "github.com/sqls-server/sqls",
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/sqls-server/sqls",
                    "Go SQL language server with a stable one-binary install path.",
                ),
                github_release_entry(
                    "postgres-language-server",
                    "Postgres Language Server",
                    LanguageKind::PostgresSql,
                    "postgrestools",
                    &["postgrestools"],
                    POSTGRES_LS_VERSION,
                    &POSTGRES_LS_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/supabase-community/postgres-language-server",
                    "Postgres-focused LSP uses libpg_query for parser fidelity and is the strongest Postgres-specific option.",
                ),
                go_entry(
                    "promql-langserver",
                    "promql-langserver",
                    LanguageKind::PromQl,
                    "promql-langserver",
                    &["promql-langserver"],
                    "latest",
                    "github.com/prometheus-community/promql-langserver/cmd/promql-langserver",
                    Footprint::Low,
                    Maturity::Preview,
                    "https://github.com/prometheus-community/promql-langserver",
                    "PromQL-specific LSP with a Go module path and compact footprint.",
                ),
                npm_entry(
                    "openapi-yaml-language-server",
                    "yaml-language-server (OpenAPI schemas)",
                    LanguageKind::OpenApi,
                    "yaml-language-server",
                    &["yaml-language-server"],
                    "latest",
                    &["yaml-language-server"],
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/redhat-developer/yaml-language-server",
                    "OpenAPI support is best handled through YAML/JSON schema-aware language service rather than a weaker abandoned OpenAPI-only server.",
                ),
                github_release_entry(
                    "glsl-analyzer",
                    "glsl_analyzer",
                    LanguageKind::Glsl,
                    "glsl_analyzer",
                    &["glsl_analyzer"],
                    GLSL_ANALYZER_VERSION,
                    &GLSL_ANALYZER_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/nolanderc/glsl_analyzer",
                    "Rust-based GLSL analyzer with lower footprint than older C++ servers.",
                ),
                github_release_entry(
                    "wgsl-analyzer",
                    "wgsl-analyzer",
                    LanguageKind::Wgsl,
                    "wgsl-analyzer",
                    &["wgsl_analyzer", "wgsl-analyzer"],
                    WGSL_ANALYZER_VERSION,
                    &WGSL_ANALYZER_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/wgsl-analyzer/wgsl-analyzer",
                    "Dedicated WGSL language server for WebGPU shader code.",
                ),
                manual_entry(
                    "hlsl-tools",
                    "HLSL Tools",
                    LanguageKind::Hlsl,
                    "hlsl-tools",
                    &["hlsl-tools"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/tgjones/HlslTools",
                    "Most mature open HLSL language tooling surfaced by public LSP registries.",
                    "Install HLSL Tools with upstream instructions and ensure the language server command is on PATH.",
                ),
                manual_entry(
                    "qmlls",
                    "qmlls",
                    LanguageKind::Qml,
                    "qmlls",
                    &["qmlls"],
                    "system",
                    Footprint::Toolchain,
                    Maturity::Stable,
                    "https://github.com/qt/qtdeclarative",
                    "Official Qt QML language server shipped with Qt tooling.",
                    "Install Qt/QML tooling and ensure `qmlls` is on PATH.",
                ),
                github_release_entry(
                    "opencl-language-server",
                    "opencl-language-server",
                    LanguageKind::OpenCl,
                    "opencl-language-server",
                    &["opencl-language-server"],
                    OPENCL_LS_VERSION,
                    &OPENCL_LS_RELEASE_SPEC,
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/Galarius/opencl-language-server",
                    "Dedicated OpenCL language server.",
                ),
                github_release_entry(
                    "verible",
                    "Verible Verilog Language Server",
                    LanguageKind::SystemVerilog,
                    "verible-verilog-ls",
                    &["verible-verilog-ls"],
                    VERIBLE_VERSION,
                    &VERIBLE_RELEASE_SPEC,
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/chipsalliance/verible",
                    "CHIPS Alliance Verible is the best maintained open SystemVerilog LSP/tooling suite.",
                ),
                github_release_entry(
                    "vhdl-ls",
                    "vhdl_ls",
                    LanguageKind::Vhdl,
                    "vhdl_ls",
                    &["vhdl_ls"],
                    VHDL_LS_VERSION,
                    &VHDL_LS_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/VHDL-LS/rust_hdl",
                    "Open VHDL language server with a compact Rust binary.",
                ),
                github_release_entry(
                    "veryl-ls",
                    "Veryl Language Server",
                    LanguageKind::Veryl,
                    "veryl-ls",
                    &["veryl-ls"],
                    VERYL_LS_VERSION,
                    &VERYL_LS_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/veryl-lang/veryl",
                    "Official Veryl language server.",
                ),
                npm_entry(
                    "dot-language-server",
                    "dot-language-server",
                    LanguageKind::Dot,
                    "dot-language-server",
                    &["dot-language-server"],
                    "latest",
                    &["dot-language-server"],
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/nikeee/dot-language-server",
                    "Small Graphviz DOT language server with npm packaging.",
                ),
                github_release_entry(
                    "marksman",
                    "Marksman",
                    LanguageKind::Markdown,
                    "marksman",
                    &["marksman"],
                    MARKSMAN_VERSION,
                    &MARKSMAN_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/artempyanykh/marksman",
                    "Markdown LSP with strong cross-editor support; Mermaid-specific standalone LSPs remain too thin.",
                ),
                github_release_entry(
                    "texlab",
                    "texlab",
                    LanguageKind::Latex,
                    "texlab",
                    &["texlab"],
                    TEXLAB_VERSION,
                    &TEXLAB_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/latex-lsp/texlab",
                    "Mature LaTeX language server with broad editor adoption.",
                ),
                github_release_entry(
                    "tinymist",
                    "tinymist",
                    LanguageKind::Typst,
                    "tinymist",
                    &["tinymist"],
                    TINYMIST_VERSION,
                    &TINYMIST_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/Myriad-Dreamin/tinymist",
                    "Actively maintained Typst language server that supersedes older typst-lsp choices.",
                ),
                manual_entry(
                    "robotcode",
                    "RobotCode",
                    LanguageKind::RobotFramework,
                    "robotcode",
                    &["robotcode"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/robotcodedev/robotcode",
                    "Robot Framework language server with active tooling support.",
                    "Install RobotCode with pipx or upstream instructions and ensure `robotcode` is on PATH.",
                ),
                npm_entry(
                    "cucumber-language-server",
                    "Cucumber Language Server",
                    LanguageKind::Gherkin,
                    "cucumber-language-server",
                    &["cucumber-language-server"],
                    "latest",
                    &["@cucumber/language-server"],
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/cucumber/language-server",
                    "Official Cucumber/Gherkin language server with npm packaging.",
                ),
                github_release_entry(
                    "regal",
                    "Regal",
                    LanguageKind::Rego,
                    "regal",
                    &["regal"],
                    REGAL_VERSION,
                    &REGAL_RELEASE_SPEC,
                    Footprint::Low,
                    Maturity::Stable,
                    "https://github.com/StyraInc/regal",
                    "Regal provides the maintained Rego language server path from the OPA ecosystem.",
                ),
                manual_entry(
                    "puppet-editor-services",
                    "Puppet Editor Services",
                    LanguageKind::Puppet,
                    "puppet-languageserver",
                    &["puppet-languageserver"],
                    "system",
                    Footprint::Medium,
                    Maturity::Stable,
                    "https://github.com/lingua-pupuli/puppet-editor-services",
                    "Maintained Puppet language server from the Puppet community.",
                    "Install Puppet Editor Services and ensure `puppet-languageserver` is on PATH.",
                ),
            ],
        }
    }

    pub fn all(&self) -> &[ServerEntry] {
        &self.entries
    }

    pub fn by_id(&self, id: &str) -> Option<&ServerEntry> {
        self.entries
            .iter()
            .find(|entry| entry.id.eq_ignore_ascii_case(id))
    }

    pub fn for_language(&self, language: LanguageKind) -> Vec<&ServerEntry> {
        self.entries
            .iter()
            .filter(|entry| entry.language == language)
            .collect()
    }
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Footprint {
    Low,
    Medium,
    High,
    Toolchain,
}

impl Footprint {
    pub fn label(self) -> &'static str {
        match self {
            Self::Low => "Low",
            Self::Medium => "Medium",
            Self::High => "High",
            Self::Toolchain => "Toolchain-bound",
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Maturity {
    Stable,
    Preview,
}

impl Maturity {
    pub fn label(self) -> &'static str {
        match self {
            Self::Stable => "Stable",
            Self::Preview => "Preview",
        }
    }
}

#[derive(Debug)]
pub struct ServerEntry {
    pub id: &'static str,
    pub name: &'static str,
    pub language: LanguageKind,
    pub binary: &'static str,
    pub aliases: &'static [&'static str],
    pub version: &'static str,
    pub install_method: InstallMethod,
    pub footprint: Footprint,
    pub maturity: Maturity,
    pub source_url: &'static str,
    pub rationale: &'static str,
}

impl ServerEntry {
    pub fn install_id(&self) -> &'static str {
        match self.id {
            "javascript-language-server" => "typescript-language-server",
            "css-language-server" | "html-language-server" | "json-language-server" => {
                "vscode-langservers-extracted"
            }
            "openapi-yaml-language-server" => "yaml-language-server",
            _ => self.id,
        }
    }
}

#[derive(Debug)]
pub enum InstallMethod {
    Npm { packages: &'static [&'static str] },
    GoInstall { module: &'static str },
    DotnetTool { package: &'static str },
    Gem { package: &'static str },
    Pipx { package: &'static str },
    GithubReleaseArchive { spec: &'static GithubReleaseSpec },
    Manual { instructions: &'static str },
}

impl InstallMethod {
    pub fn is_managed(&self) -> bool {
        !matches!(self, Self::Manual { .. })
    }

    pub fn is_supported_on_current_platform(&self) -> bool {
        match self {
            Self::GithubReleaseArchive { spec } => {
                super::github_release::is_supported_on_current_platform(spec)
            }
            _ => true,
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            Self::Npm { .. } => "npm",
            Self::GoInstall { .. } => "go install",
            Self::DotnetTool { .. } => "dotnet tool",
            Self::Gem { .. } => "gem",
            Self::Pipx { .. } => "pipx",
            Self::GithubReleaseArchive { .. } => "github release",
            Self::Manual { .. } => "system/manual",
        }
    }

    pub fn manual_instructions(&self) -> Option<&'static str> {
        match self {
            Self::Manual { instructions } => Some(*instructions),
            Self::GithubReleaseArchive { spec }
                if !super::github_release::is_supported_on_current_platform(spec) =>
            {
                Some(
                    "No managed GitHub release archive is configured for this platform. Install the upstream binary and put it on PATH.",
                )
            }
            _ => None,
        }
    }

    pub fn install_warning(&self) -> Option<&'static str> {
        match self {
            Self::GithubReleaseArchive { spec } => spec.install_warning,
            _ => None,
        }
    }
}

fn npm_entry(
    id: &'static str,
    name: &'static str,
    language: LanguageKind,
    binary: &'static str,
    aliases: &'static [&'static str],
    version: &'static str,
    packages: &'static [&'static str],
    footprint: Footprint,
    maturity: Maturity,
    source_url: &'static str,
    rationale: &'static str,
) -> ServerEntry {
    entry(
        id,
        name,
        language,
        binary,
        aliases,
        version,
        InstallMethod::Npm { packages },
        footprint,
        maturity,
        source_url,
        rationale,
    )
}

fn go_entry(
    id: &'static str,
    name: &'static str,
    language: LanguageKind,
    binary: &'static str,
    aliases: &'static [&'static str],
    version: &'static str,
    module: &'static str,
    footprint: Footprint,
    maturity: Maturity,
    source_url: &'static str,
    rationale: &'static str,
) -> ServerEntry {
    entry(
        id,
        name,
        language,
        binary,
        aliases,
        version,
        InstallMethod::GoInstall { module },
        footprint,
        maturity,
        source_url,
        rationale,
    )
}

fn dotnet_entry(
    id: &'static str,
    name: &'static str,
    language: LanguageKind,
    binary: &'static str,
    aliases: &'static [&'static str],
    version: &'static str,
    package: &'static str,
    footprint: Footprint,
    maturity: Maturity,
    source_url: &'static str,
    rationale: &'static str,
) -> ServerEntry {
    entry(
        id,
        name,
        language,
        binary,
        aliases,
        version,
        InstallMethod::DotnetTool { package },
        footprint,
        maturity,
        source_url,
        rationale,
    )
}

fn gem_entry(
    id: &'static str,
    name: &'static str,
    language: LanguageKind,
    binary: &'static str,
    aliases: &'static [&'static str],
    version: &'static str,
    package: &'static str,
    footprint: Footprint,
    maturity: Maturity,
    source_url: &'static str,
    rationale: &'static str,
) -> ServerEntry {
    entry(
        id,
        name,
        language,
        binary,
        aliases,
        version,
        InstallMethod::Gem { package },
        footprint,
        maturity,
        source_url,
        rationale,
    )
}

fn pipx_entry(
    id: &'static str,
    name: &'static str,
    language: LanguageKind,
    binary: &'static str,
    aliases: &'static [&'static str],
    version: &'static str,
    package: &'static str,
    footprint: Footprint,
    maturity: Maturity,
    source_url: &'static str,
    rationale: &'static str,
) -> ServerEntry {
    entry(
        id,
        name,
        language,
        binary,
        aliases,
        version,
        InstallMethod::Pipx { package },
        footprint,
        maturity,
        source_url,
        rationale,
    )
}

fn github_release_entry(
    id: &'static str,
    name: &'static str,
    language: LanguageKind,
    binary: &'static str,
    aliases: &'static [&'static str],
    version: &'static str,
    spec: &'static GithubReleaseSpec,
    footprint: Footprint,
    maturity: Maturity,
    source_url: &'static str,
    rationale: &'static str,
) -> ServerEntry {
    entry(
        id,
        name,
        language,
        binary,
        aliases,
        version,
        InstallMethod::GithubReleaseArchive { spec },
        footprint,
        maturity,
        source_url,
        rationale,
    )
}

fn manual_entry(
    id: &'static str,
    name: &'static str,
    language: LanguageKind,
    binary: &'static str,
    aliases: &'static [&'static str],
    version: &'static str,
    footprint: Footprint,
    maturity: Maturity,
    source_url: &'static str,
    rationale: &'static str,
    instructions: &'static str,
) -> ServerEntry {
    entry(
        id,
        name,
        language,
        binary,
        aliases,
        version,
        InstallMethod::Manual { instructions },
        footprint,
        maturity,
        source_url,
        rationale,
    )
}

fn entry(
    id: &'static str,
    name: &'static str,
    language: LanguageKind,
    binary: &'static str,
    aliases: &'static [&'static str],
    version: &'static str,
    install_method: InstallMethod,
    footprint: Footprint,
    maturity: Maturity,
    source_url: &'static str,
    rationale: &'static str,
) -> ServerEntry {
    ServerEntry {
        id,
        name,
        language,
        binary,
        aliases,
        version,
        install_method,
        footprint,
        maturity,
        source_url,
        rationale,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::language::Language;

    #[test]
    fn every_language_has_a_registry_entry() {
        for kind in Language::ALL {
            assert!(
                !REGISTRY.for_language(*kind).is_empty(),
                "missing server entry for {:?}",
                kind
            );
        }
    }

    #[test]
    fn javascript_and_typescript_share_the_ts_server() {
        let ts = REGISTRY.for_language(LanguageKind::TypeScript)[0];
        let js = REGISTRY.for_language(LanguageKind::JavaScript)[0];
        assert_eq!(ts.name, "typescript-language-server");
        assert_eq!(ts.name, js.name);
        assert_eq!(ts.install_id(), js.install_id());
    }

    #[test]
    fn extracted_vscode_servers_share_one_install_root() {
        let html = REGISTRY.by_id("html-language-server").unwrap();
        let css = REGISTRY.by_id("css-language-server").unwrap();
        let json = REGISTRY.by_id("json-language-server").unwrap();

        assert_eq!(html.install_id(), "vscode-langservers-extracted");
        assert_eq!(html.install_id(), css.install_id());
        assert_eq!(html.install_id(), json.install_id());
    }

    #[test]
    fn toolchain_hosted_manual_servers_do_not_probe_generic_hosts() {
        for id in [
            "julia-language-server",
            "powershell-editor-services",
            "r-languageserver",
        ] {
            let entry = REGISTRY.by_id(id).unwrap();
            let probes = entry
                .aliases
                .iter()
                .copied()
                .chain(std::iter::once(entry.binary))
                .collect::<Vec<_>>();

            assert!(!probes.contains(&"julia"));
            assert!(!probes.contains(&"R"));
            assert!(!probes.contains(&"Rscript"));
            assert!(!probes.contains(&"pwsh"));
            assert!(!probes.contains(&"powershell"));
        }
    }

    #[test]
    fn ada_language_server_uses_managed_github_release_archive() {
        let entry = REGISTRY.by_id("ada-language-server").unwrap();

        assert_eq!(entry.install_method.label(), "github release");
        assert!(entry.install_method.is_managed());
        assert!(entry.install_method.is_supported_on_current_platform());
    }

    #[test]
    fn promoted_guide_servers_use_github_release_installs() {
        for id in [
            "rust-analyzer",
            "clangd",
            "lua-language-server",
            "clojure-lsp",
            "deno-lsp",
            "expert",
            "nimlangserver",
            "perl-navigator",
            "v-analyzer",
            "zls",
            "serve-d",
            "gleam-lsp",
            "millet",
            "taplo",
            "docker-language-server",
            "cue-lsp",
            "kcl-language-server",
            "helm-ls",
            "neocmakelsp",
            "mesonlsp",
            "just-lsp",
            "buf-language-server",
            "postgres-language-server",
            "glsl-analyzer",
            "wgsl-analyzer",
            "opencl-language-server",
            "verible",
            "vhdl-ls",
            "veryl-ls",
            "marksman",
            "texlab",
            "tinymist",
            "regal",
        ] {
            let entry = REGISTRY.by_id(id).unwrap();

            assert_eq!(entry.install_method.label(), "github release", "{id}");
            assert!(entry.install_method.is_managed(), "{id}");
        }
    }

    #[test]
    fn large_release_installs_surface_warning() {
        let entry = REGISTRY.by_id("clangd").unwrap();

        assert!(entry.install_method.install_warning().is_some());
    }
}
